# ======================================================================================
# Copyright (C) 2019 Nordix Foundation.
# Modifications Copyright (c) 2019-2020 AT&T Intellectual Property. All rights reserved.
# ======================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limits under the License.
# ============LICENSE_END===============================================================
---
version: "3.4"
services:
  lum-database:
    build:
      context: './lum-db/'
      args:
        SVRVERSION: '${SVRVERSION}'
    # replace username/repo:tag with your name and image details
    image: 'acumos/lum-database:${SVRVERSION?SVRVERSION needs to be set with the version of the license usage manager server}'
    ports:
      - "5432:5432"
  lum-server:
    build:
      context: ./lum-server/
      target: build-stage
      args:
        BUILD_DEVELOPMENT: '1'
        SVRVERSION: '${SVRVERSION}'
    command: npm run start:dev
    # replace username/repo:tag with your name and image details
    image: 'acumos/lum-server:${SVRVERSION?SVRVERSION needs to be set with the version of the license usage manager server}'
    depends_on:
      - lum-database
    ports:
      - "2080:2080"
      - "5858:5858"
    volumes:
      - ./lum-server/src:/work/src
